#ifndef DATA_H_INCLUDED
#define DATA_H_INCLUDED

#include<iostream>
#include<cmath>
#include<limits>
#include<string>

///External Define to indicate Windows Version...
#define _WIN32_WINNT 0x0500

#include<windows.h>

/// Basic Colors - FOREGROUND

#define RED            FOREGROUND_RED|FOREGROUND_INTENSITY
#define BROWN          FOREGROUND_RED
#define GREEN          FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define DARK_GREEN     FOREGROUND_GREEN
#define BLUE           FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define DARK_BLUE      FOREGROUND_BLUE
#define YELLOW         FOREGROUND_GREEN|FOREGROUND_RED|FOREGROUND_INTENSITY
#define TURQUOISE      FOREGROUND_GREEN|FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define DARK_TURQUOISE FOREGROUND_GREEN|FOREGROUND_BLUE
#define PINK           FOREGROUND_BLUE|FOREGROUND_RED|FOREGROUND_INTENSITY
#define PURPLE         FOREGROUND_BLUE|FOREGROUND_RED
#define OLIVE          FOREGROUND_GREEN|FOREGROUND_RED
#define WHITE          FOREGROUND_GREEN|FOREGROUND_RED|FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define GRAY           FOREGROUND_GREEN|FOREGROUND_RED|FOREGROUND_BLUE
#define DARK_GRAY      FOREGROUND_INTENSITY
#define BLACK          0

/// Basic Colors - BACKGROUND

#define BGRED            BACKGROUND_RED|BACKGROUND_INTENSITY
#define BGBROWN          BACKGROUND_RED
#define BGGREEN          BACKGROUND_GREEN|BACKGROUND_INTENSITY
#define BGDARK_GREEN     BACKGROUND_GREEN
#define BGBLUE           BACKGROUND_BLUE|BACKGROUND_INTENSITY
#define BGDARK_BLUE      BACKGROUND_BLUE
#define BGYELLOW         BACKGROUND_GREEN|BACKGROUND_RED|BACKGROUND_INTENSITY
#define BGTURQUOISE      BACKGROUND_GREEN|BACKGROUND_BLUE|BACKGROUND_INTENSITY
#define BGDARK_TURQUOISE BACKGROUND_GREEN|BACKGROUND_BLUE
#define BGPINK           BACKGROUND_BLUE|BACKGROUND_RED|BACKGROUND_INTENSITY
#define BGPURPLE         BACKGROUND_BLUE|BACKGROUND_RED
#define BGOLIVE          BACKGROUND_GREEN|BACKGROUND_RED
#define BGWHITE          BACKGROUND_GREEN|BACKGROUND_RED|BACKGROUND_BLUE|BACKGROUND_INTENSITY
#define BGGRAY           BACKGROUND_GREEN|BACKGROUND_RED|BACKGROUND_BLUE
#define BGDARK_GRAY      BACKGROUND_INTENSITY

const bool HIGH = 1;
const bool LOW  = 0;

///Single Character Width
const double cW = 837.0/80.0;
///Single Character Height
const double cH = 523.0/30.0;

unsigned char UC = 0xCA,DC = 0xCB,ULB = 201,DLB = 200,URB = 187,DRB = 188,HT = 205,VT = 186,LC = 0xCC,RC = 0xB9,NC = 0xCE, BLK = 219;

/// Global Variables

HANDLE out=GetStdHandle(STD_OUTPUT_HANDLE);
HANDLE in =GetStdHandle(STD_INPUT_HANDLE);
CONSOLE_SCREEN_BUFFER_INFO csbi;
CONSOLE_CURSOR_INFO     cursorInfo;
WORD ORIGINAL;
HWND CONSOLE;
RECT R;
COORD CONSOLECOORD;
DWORD ConsoleMode;

#endif // KV_AIRLINES_DATA_H_INCLUDED
